name: Windows Compile

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Install dependencies
        run: |
          choco install ninja
          Remove-Item -Path "C:\ProgramData\Chocolatey\bin\ccache.exe" -Force -ErrorAction SilentlyContinue
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.14
        with:
          variant: sccache
          key: ${{ runner.os }}-ccache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ github.ref }}
            ${{ runner.os }}-ccache-
      - name: Cache build folder
        uses: actions/cache@v4
        with:
          save-always: true
          key: ${{ runner.os }}-build-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.ref }}
            ${{ runner.os }}-build-
          path: |
            build/x64
            D:/a/vcpkg
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        env:
          VCPKG_ROOT: D:/a/vcpkg
        run: |
          set $env:PATH="$env:USERPROFILE/.cargo/bin;$env:PATH"
          cmake --no-warn-unused-cli -S . -B "build/x64" -G Ninja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_BUILD_TYPE:STRING=Release -DUSE_AUTO_VCPKG=ON -DCMAKE_VS_PLATFORM_NAME=x64 -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          cmake --build ./build/x64 --parallel 1
      - name: Create Package
        run: |
          (cd build/x64 && cpack)
          cd ../..
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ultra-viewer-windows
          path: ./build/x64/Debug
